Repository MeeTeamIdle/MeeTeam_BackEnd, pull requests merged in 2024-04, with the labels that each got.

#164 [CHORE] 코드 마이그레이션
  src/main/java/synk/meeteam/domain/common/course/entity/Course.java
  src/main/java/synk/meeteam/domain/common/course/entity/Professor.java
  src/main/java/synk/meeteam/domain/common/course/repository/CourseRepository.java
  src/main/java/synk/meeteam/domain/common/course/repository/ProfessorRepository.java
  src/main/java/synk/meeteam/domain/common/course/service/CourseService.java
  src/main/java/synk/meeteam/domain/common/course/service/ProfessorService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/service/RecruitmentTagService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/service/vo/RecruitmentTagVO.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_tag/RecruitmentTagServiceTest.java
  src/test/java/synk/meeteam/global/enums/EnumsTest.java
Labels: Priority: Critical, Status: Available, Type: Feature

#162 [DOCS] 오픈카톡방 링크 설정 API 스웨거 PR
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/SetLinkRequestDto.java
Labels: Priority: High, Status: Available, Type: Document

#167 [FEAT] 링크 설정 API
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantException.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
Labels: Priority: High, Status: Available, Type: Feature

#179 [DOCS] 신청자 승인 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/ApproveApplicantRequestDto.java
Labels: Priority: High, Status: Available, Type: Document

#173 [FEAT] 댓글 삭제 API
  src/main/java/synk/meeteam/domain/common/course/entity/Professor.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/entity/RecruitmentComment.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/exception/RecruitmentCommentExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/repository/RecruitmentCommentRepositoryCustomImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/vo/RecruitmentCommentVO.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/DeleteCommentRequestDto.java
  src/main/java/synk/meeteam/global/util/Encryption.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
Labels: Priority: High, Status: Available, Type: Feature

#183 [FEAT] 댓글 수정 API
  build.gradle
  src/main/java/synk/meeteam/domain/common/role/dto/RoleDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantInfoResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetRoleDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/entity/RecruitmentComment.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/ModifyCommentRequestDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_comment/RecruitmentCommentServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
Labels: Priority: High, Status: Available, Type: Feature

#187 [DOCS] 신청자 거절 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/request/ProcessApplicantRequestDto.java
Labels: Priority: High, Status: Available, Type: Document

#189 [DOCS] 신청자 목록 조회 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java
Labels: Priority: High, Status: Available, Type: Document

#185 [FEAT] 신청자 승인 API
  build.gradle
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitStatus.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
  src/main/java/synk/meeteam/infra/mail/MailService.java
  src/main/java/synk/meeteam/infra/mail/MailText.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantFixture.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleRepositoryTest.java
Labels: Priority: High, Status: Available, Type: Feature

#191 [FIX] 구인 로직 전체적인 수정
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/DeleteCommentRequestDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentRoleResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/global/common/exception/GlobalExceptionHandler.java
  src/main/java/synk/meeteam/global/common/exception/GlobalExceptionType.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
Labels: Priority: Critical, Status: Available, Type: Fix

#192 [FEAT] 신청자 목록 조회 API
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/global/util/Encryption.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
Labels: Priority: High, Status: Available, Type: Feature

#194 [FEAT] 신청자 거절 API
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
Labels: Priority: High, Status: Available, Type: Feature

#196 [DOCS] 구인 신청 취소 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
Labels: Priority: High, Status: Available, Type: Document

#200 [FIX] html 코드 주입 작업 추가
  .github/workflows/deploy.yml
Labels: Priority: Critical, Status: Available, Type: Fix

#203 [FIX] html 생성 작업 수정
  .github/workflows/deploy.yml
Labels: Priority: Critical, Type: Fix

#205 [FIX] 신청자 목록 조회 수정
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostSearchRepositoryTest.java
Labels: Priority: Critical, Type: Fix

#215 [FEAT] 구인 신청 취소 API
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/DeleteStatus.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/exception/RecruitmentApplicantExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/exception/RecruitmentRoleExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleServiceTest.java
Labels: Priority: High, Status: Available, Type: Feature

#217 [FEAT] PreSignedUrl 서비스 로직에 맞게 구현
  src/main/java/synk/meeteam/domain/portfolio/portfolio/exception/PortfolioExceptionType.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
  src/main/java/synk/meeteam/global/api/ServerProfileController.java
  src/main/java/synk/meeteam/global/dto/PreSignedUrlRequestDto.java
  src/main/java/synk/meeteam/global/entity/ServiceType.java
  src/main/java/synk/meeteam/infra/s3/service/S3Service.java
  src/main/java/synk/meeteam/infra/s3/service/vo/PreSignedUrlVO.java
  src/test/java/synk/meeteam/domain/user/user/UserFixture.java
Labels: Priority: Critical, Type: Fix

#218 [FEAT] 포트폴리오 등록, 조회, 수정 API 구현
  src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioApi.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/api/PortfolioController.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/command/CreatePortfolioCommand.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/command/PortfolioCommandMapper.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/command/UpdatePortfolioCommand.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/CreatePortfolioRequestDto.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/UpdatePortfolioRequestDto.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/response/GetPortfolioResponseDto.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/exception/PortfolioExceptionType.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/repository/PortfolioRepository.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioFacade.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioService.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio/service/PortfolioServiceImpl.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_link/entity/PortfolioLink.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_link/repository/PortfolioLinkRepository.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_link/service/PortfolioLinkService.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/entity/PortfolioSkill.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/repository/PortfolioSkillRepository.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/repository/dummy.txt
  src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/service/PortfolioSkillService.java
  src/main/java/synk/meeteam/domain/portfolio/portfolio_skill/service/dummy.txt
  src/main/java/synk/meeteam/global/api/ServerProfileController.java
  src/main/java/synk/meeteam/global/util/StringListConverter.java
  src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioFixture.java
  src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioRepositoryTest.java
  src/test/java/synk/meeteam/domain/portfolio/portfolio/PortfolioServiceTest.java
Labels: Priority: High, Type: Feature

#222 [FIX] 수업, 교수 저장 방식 수정
  src/main/java/synk/meeteam/domain/common/course/repository/CourseRepository.java
  src/main/java/synk/meeteam/domain/common/course/repository/ProfessorRepository.java
  src/main/java/synk/meeteam/domain/common/course/service/CourseService.java
  src/main/java/synk/meeteam/domain/common/course/service/ProfessorService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
Labels: Priority: Critical, Status: Available, Type: Bug

#226 [FEAT] 디스코드 로깅봇 구현
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/java/synk/meeteam/global/common/exception/GlobalExceptionHandler.java
  src/main/java/synk/meeteam/infra/discord/DiscordAppender.java
  src/main/java/synk/meeteam/infra/discord/DiscordWebHook.java
  src/main/java/synk/meeteam/infra/discord/entity/Author.java
  src/main/java/synk/meeteam/infra/discord/entity/EmbedObject.java
  src/main/java/synk/meeteam/infra/discord/entity/Field.java
  src/main/java/synk/meeteam/infra/discord/entity/Footer.java
  src/main/java/synk/meeteam/infra/discord/entity/Image.java
  src/main/java/synk/meeteam/infra/discord/entity/JsonObject.java
  src/main/java/synk/meeteam/infra/discord/entity/Thumbnail.java
  src/main/java/synk/meeteam/infra/discord/exception/ErrorLogAppenderException.java
  src/main/java/synk/meeteam/infra/discord/exception/ErrorLogAppenderExceptionType.java
  src/main/java/synk/meeteam/infra/discord/filter/CachedBodyRequestWrapper.java
  src/main/java/synk/meeteam/infra/discord/filter/CachedBodyServletInputStream.java
  src/main/java/synk/meeteam/infra/discord/filter/FilterConfig.java
  src/main/java/synk/meeteam/infra/discord/filter/MDCFilter.java
  src/main/java/synk/meeteam/infra/discord/filter/ServletWrappingFilter.java
  src/main/java/synk/meeteam/infra/discord/util/ApiCallUtil.java
  src/main/java/synk/meeteam/infra/discord/util/HttpRequestUtil.java
  src/main/java/synk/meeteam/infra/discord/util/MDCUtil.java
  src/main/java/synk/meeteam/infra/discord/util/StringUtil.java
  src/main/resources/console-appender.xml
  src/main/resources/discord-appender.xml
  src/main/resources/logback-spring.xml
Labels: Priority: High, Type: Feature

#228 [FIX] 작성자 여부 확인 코드 수정
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
Labels: Priority: Critical

#239 [ADD] 처음 접속 여부 추가
  src/main/java/synk/meeteam/domain/user/user/entity/User.java
Labels: Priority: Critical

#243 [FIX] 구인글 생성 로직 수정
  src/main/java/synk/meeteam/domain/common/course/service/CourseService.java
  src/main/java/synk/meeteam/domain/common/course/service/ProfessorService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
Labels: Priority: Critical, Type: Fix

#235 [FEAT] 로컬 spring에서 rds 연결 가능하도록 구현
  build.gradle
  src/main/java/synk/meeteam/infra/rds/SshDataSourceConfig.java
  src/main/java/synk/meeteam/infra/rds/SshTunnelingInitializer.java
  src/main/resources/logback-spring.xml
Labels: Priority: High

#246 [FEAT] 구인글 삭제 API 구현
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/DeleteStatus.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantCustomRepositoryImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/repository/RecruitmentPostRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/global/entity/DeleteStatus.java
Labels: Priority: High, Status: Available, Type: Feature

#237 [INFRA] AOP 활용한 로깅 시스템 구축
  build.gradle
  docker/docker-compose.blue.yml
  docker/docker-compose.green.yml
  src/main/java/synk/meeteam/MeeteamApplication.java
  src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: Priority: High, Type: Infra

#248 [FEAT] 최초 접근 기능 구현
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/api/RecruitmentApplicantController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/dto/response/GetApplicantInfoResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/user/user/entity/User.java
  src/main/java/synk/meeteam/domain/user/user/service/UserService.java
  src/main/java/synk/meeteam/domain/user/user/service/UserServiceImpl.java
Labels: Priority: Critical, Status: Available, Type: Feature

#258 [FIX] 포인트컷 수정
  src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java
Labels: Priority: Critical, Type: Bug

#262 [FIX] Object 리턴하도록 수정
  src/main/java/synk/meeteam/global/aop/ExecutionLoggingAop.java
Labels: Priority: Critical

#267 [FIX] 여러 수정사항들 반영
  .github/workflows/deploy.yml
  build.gradle
  scripts/deploy.sh
  src/main/java/synk/meeteam/domain/auth/api/AuthController.java
  src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseDto.java
  src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseMapper.java
  src/main/java/synk/meeteam/domain/auth/service/vo/AuthUserVo.java
  src/main/java/synk/meeteam/domain/common/skill/exception/SkillExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
  src/main/java/synk/meeteam/global/api/ServerProfileController.java
  src/main/java/synk/meeteam/global/common/exception/GlobalExceptionHandler.java
  src/main/java/synk/meeteam/infra/mail/MailService.java
  src/main/java/synk/meeteam/infra/mail/MailText.java
  src/main/java/synk/meeteam/infra/s3/service/S3Service.java
  src/main/java/synk/meeteam/security/jwt/service/JwtService.java
Labels: Priority: Critical, Type: Bug, Type: Feature

#276 [ REFACTOR] 메일 비동기 전송 구현
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/facade/RecruitmentApplicantFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/global/config/AsyncConfig.java
  src/main/java/synk/meeteam/infra/mail/MailService.java
Labels: Priority: Medium, Type: Refactor

#288 [CHORE] 디스코드 알림 봇 수정
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: Priority: Medium

#291 [CHORE] cors 수정
  src/main/java/synk/meeteam/security/config/SecurityConfig.java
Labels: Priority: Critical

#293 [FIX] cd 수정
  .github/workflows/deploy.yml
Labels: Priority: Critical

#298 [FIX] 파일 확장자 제거 로직 추가
  src/main/java/synk/meeteam/global/api/ServerProfileController.java
Labels: Priority: Critical, Status: Available, Type: Fix

#300 [ADD] jpeg 추가
  src/main/java/synk/meeteam/domain/portfolio/portfolio/dto/request/CreatePortfolioRequestDto.java
Labels: Priority: Critical

#302 [CHORE] 구인역할 스킬없는 경우 대응
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
Labels: Priority: Critical, Status: Available, Type: Chore

#304 [CHORE] 이메일 인증 후 중복회원 가입 방지 추가
  src/main/java/synk/meeteam/domain/auth/api/AuthController.java
  src/main/java/synk/meeteam/domain/auth/exception/AuthExceptionType.java
  src/main/java/synk/meeteam/domain/auth/service/AuthService.java
  src/main/java/synk/meeteam/infra/mail/MailService.java
Labels: Priority: Critical, Type: Bug
