Repository MeeTeamIdle/MeeTeam_BackEnd, pull requests merged in 2024-03, with the labels that each got.

#96 [FEAT] 구인신청 API
  src/main/java/synk/meeteam/domain/common/role/repository/RoleRepositoryCustom.java
  src/main/java/synk/meeteam/domain/common/role/repository/RoleRepositoryCustomImpl.java
  src/main/java/synk/meeteam/domain/common/role/service/RoleService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/entity/RecruitmentApplicant.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/RecruitmentApplicantRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/repository/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/RecruitmentApplicantService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_applicant/service/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/ApplyRecruitmentRequestDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/applyRecruitmentRequestDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetApplyInfoResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/dto/AvailableRecruitmentRoleDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/dto/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/exception/RecruitmentRoleException.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/exception/RecruitmentRoleExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/exception/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepositoryCustom.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepositoryCustomImpl.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
  src/test/java/synk/meeteam/domain/DatabaseCleanUp.java
  src/test/java/synk/meeteam/domain/common/role/RoleRepositoryTest.java
  src/test/java/synk/meeteam/domain/common/role/RoleServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantFixture.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_applicant/RecruitmentApplicantServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleServiceTest.java
  src/test/java/synk/meeteam/domain/user/user/UserFixtures.java
Labels: Priority: High, Status: Available, Type: Feature

#100 [FEAT] 구인마감 구현
  src/main/java/synk/meeteam/domain/portfolio/portfolio/entity/Portfolio.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/exception/RecruitmentPostExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/domain/user/user/entity/User.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostControllerTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
Labels: Priority: High, Status: Available, Type: Feature

#103 [CHORE] 변수명 및 변수타입 변경
  src/main/java/synk/meeteam/domain/auth/api/AuthController.java
  src/main/java/synk/meeteam/domain/auth/dto/request/SignUpUserRequestDto.java
  src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseDto.java
  src/main/java/synk/meeteam/domain/auth/dto/response/AuthUserResponseMapper.java
  src/main/java/synk/meeteam/domain/auth/service/vo/AuthUserVo.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/RecruitmentPostMapper.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateRecruitmentPostRequestDto.java
  src/main/java/synk/meeteam/security/jwt/service/JwtService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
Labels: Priority: Critical, Status: Available

#105 [FIX] Tags -> tags 변경
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/CreateRecruitmentPostRequestDto.java
Labels: Priority: Critical

#109 [FIX] 화이트 리스트 변경
  src/main/java/synk/meeteam/security/config/SecurityConfig.java
Labels: Priority: Critical, Type: Bug

#107 [DOCS] 구인글 수정 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
Labels: Priority: High, Status: Available, Type: Document

#114 [FIX] 온/오프라인 -> 상관없음으로 수정
  src/main/java/synk/meeteam/global/entity/ProceedType.java
Labels: Priority: Critical, Type: Bug

#116 [FIX] 구인글 조회 변수 수정
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
Labels: Priority: Critical, Type: Bug

#122 [ADD] Jacoco 세팅
  build.gradle
Labels: Priority: High, Status: Available

#119 [FEAT] 구인글 수정 API
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/entity/RecruitmentRole.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/repository/RecruitmentRoleRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role/service/RecruitmentRoleService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/entity/RecruitmentRoleSkill.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/repository/RecruitmentRoleSkillRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_role_skill/service/RecruitmentRoleSkillService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/repository/RecruitmentTagRepository.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_tag/service/RecruitmentTagService.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role/RecruitmentRoleServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role_skill/RecruitmentRoleSkillRepositoryTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_role_skill/RecruitmentRoleSkillServiceTest.java
Labels: Priority: High, Status: Available, Type: Feature

#129 [FEAT] 구인글 북마크 API
  src/main/java/synk/meeteam/domain/recruitment/bookmark/entity/Bookmark.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/exception/BookmarkException.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/exception/BookmarkExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/exception/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/BookmarkRepository.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/bookmark/service/BookmarkService.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/service/dummy.txt
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/test/java/synk/meeteam/domain/recruitment/bookmark/BookmarkServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
Labels: Priority: Medium, Status: Available, Type: Feature

#131 [DOCS] 구인글 북마크 취소 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
Labels: Priority: Medium, Status: Available, Type: Document

#138 [FEAT] 북마크 취소 API
  src/main/java/synk/meeteam/domain/recruitment/bookmark/exception/BookmarkExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/repository/BookmarkRepository.java
  src/main/java/synk/meeteam/domain/recruitment/bookmark/service/BookmarkService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/entity/RecruitmentPost.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/exception/RecruitmentPostExceptionType.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/facade/RecruitmentPostFacade.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/service/RecruitmentPostService.java
  src/test/java/synk/meeteam/domain/recruitment/bookmark/BookmarkServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostEntityTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostFixture.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostServiceTest.java
  src/test/java/synk/meeteam/domain/recruitment/recruitment_post/RecruitmentPostTest.java
  src/test/java/synk/meeteam/global/enums/EnumsTest.java
Labels: Priority: Medium, Status: Available, Type: Feature

#144 [DOCS] 구인글 목록 검색 조회 API 스웨거 작성
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/PaginationSearchPostResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/SearchRecruitmentPostsResponseDto.java
  src/main/java/synk/meeteam/global/dto/PageInfo.java
  src/main/java/synk/meeteam/security/config/SecurityConfig.java
Labels: Priority: High

#148 [FIX] 특정 구인글 조회 API 반환 데이터 수정
  src/main/java/synk/meeteam/domain/recruitment/bookmark/service/BookmarkService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_comment/service/RecruitmentCommentService.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetCommentResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetRecruitmentPostResponseDto.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/response/GetReplyResponseDto.java
  src/main/java/synk/meeteam/infra/s3/S3FileName.java
Labels: Priority: High, Status: Available, Type: Fix

#150 [FIX] UserRepository 함수 수정
  src/main/java/synk/meeteam/domain/user/user/repository/UserCustomRepositoryImpl.java
Labels: Priority: Critical

#152 [FIX] CORS delete 추가
  src/main/java/synk/meeteam/security/config/SecurityConfig.java
Labels: Priority: Critical, Type: Bug

#158 [DOCS] 댓글 삭제 API 스웨거 추가
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostApi.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/api/RecruitmentPostController.java
  src/main/java/synk/meeteam/domain/recruitment/recruitment_post/dto/request/DeleteCommentRequestDto.java
Labels: Priority: High, Status: Available, Type: Document
